### ISSUE TITLE
GitHub actions

### ISSUE THREAD

**Issue by LewisCowlesMotive** [chrispsheehan/PerformanceTestFramework#5]
Morning mate 👋 

[The first GitHub actions](https://github.com/chrispsheehan/PerformanceTestFramework/runs/7170147280?check_suite_focus=true) was the closest to passing I think, and seemed to be failing due to OpenSSL issue.

It seems this is a NodeJS 17+ problem, so either pinning to 16.x (LTS) or supplying the environment `NODE_OPTIONS=--openssl-legacy-provider` should do the trick. 👍  [source of guess](https://github.com/webpack/webpack/issues/14532)

`docker-compose.yml` is using nodejs:16.5-alpine in `master`.

It could actually be a bit deeper than that, but if it solves, let me know 👍

**Comment by LewisCowlesMotive** [comment]
```
on:
  push:
    branches:    
      - main
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
    - name: Install
      working-directory: ./src
      run: npm install
    - name: build
      working-directory: ./src
      run: npm run build
      env:
        NODE_OPTIONS: '--openssl-legacy-provider'
```

This (your first commit to create actions yaml), should do the trick (tested using the below docker-compose.yml).

```
  build:
    image: node:18-alpine
    volumes:
      - ./:/app
    command: npm run build --prefix /app
    environment:
      - 'NODE_OPTIONS=--openssl-legacy-provider'
```
